import type { Trip } from "./types";

export const demoTrip: Trip = {
  id: "demo-seongsu-1",
  title: "静かな聖水を歩く午後",
  date: "2026-08-19",
  startTime: "13:00",
  endTime: "20:10",
  budget: 80000,
  estimatedTotalCost: 61000,
  providerModes: { llm: "mock", place: "mock", crowd: "mock" },
  providerSources: { place: "mock-place", crowd: "mock-crowd" },
  warnings: ["デモモードです。場所・混雑データは実際のAPI結果ではありません。"],
  preference: {
    area: "성수",
    startTime: "13:00",
    endTime: "21:00",
    budget: 80000,
    companions: "solo",
    pace: "relaxed",
    interests: ["cafe", "select_shop", "meat"],
    preferences: ["quiet"],
    avoid: ["crowded"],
  },
  stops: [
    {
      id: "demo-stop-1",
      order: 1,
      placeId: "demo-place-1",
      placeName: "ソウルの森（デモ）",
      category: "公園",
      address: "ソウル特別市 城東区（デモ住所）",
      latitude: 37.5444,
      longitude: 127.0374,
      arrivalAt: "13:00",
      leaveAt: "14:10",
      estimatedStayMinutes: 70,
      estimatedCost: 0,
      reason:
        "落ち着いたペースで旅を始められ、聖水エリアへの移動が短いためです。",
      crowd: { level: "普通", scope: "area", areaName: "ソウルの森一帯" },
      scoreBreakdown: {
        total: 0.88,
        preference: 0.91,
        crowd: 0.86,
        distance: 0.94,
        time: 1,
        budget: 1,
        diversity: 0.7,
      },
    },
    {
      id: "demo-stop-2",
      order: 2,
      placeId: "demo-place-2",
      placeName: "静かなカフェ（デモ）",
      category: "カフェ",
      address: "ソウル特別市 城東区（デモ住所）",
      latitude: 37.5437,
      longitude: 127.0541,
      arrivalAt: "14:30",
      leaveAt: "15:40",
      estimatedStayMinutes: 70,
      estimatedCost: 12000,
      reason:
        "静かなカフェという希望と一致し、前の場所から徒歩圏内にある候補です。",
      crowd: { level: "やや混雑", scope: "area", areaName: "聖水駅一帯" },
      scoreBreakdown: {
        total: 0.85,
        preference: 0.97,
        crowd: 0.72,
        distance: 0.89,
        time: 0.95,
        budget: 0.88,
        diversity: 0.8,
      },
    },
    {
      id: "demo-stop-3",
      order: 3,
      placeId: "demo-place-3",
      placeName: "セレクトショップ（デモ）",
      category: "ショッピング",
      address: "ソウル特別市 城東区（デモ住所）",
      latitude: 37.5448,
      longitude: 127.0568,
      arrivalAt: "16:00",
      leaveAt: "17:20",
      estimatedStayMinutes: 80,
      estimatedCost: 28000,
      reason: "セレクトショップの希望を満たし、カフェから無理なく歩けます。",
      crowd: { level: "普通", scope: "area", areaName: "聖水駅一帯" },
      scoreBreakdown: {
        total: 0.81,
        preference: 0.93,
        crowd: 0.75,
        distance: 0.92,
        time: 0.9,
        budget: 0.65,
        diversity: 1,
      },
    },
    {
      id: "demo-stop-4",
      order: 4,
      placeId: "demo-place-4",
      placeName: "焼肉店（デモ）",
      category: "韓国料理",
      address: "ソウル特別市 城東区（デモ住所）",
      latitude: 37.5461,
      longitude: 127.051,
      arrivalAt: "18:20",
      leaveAt: "20:10",
      estimatedStayMinutes: 110,
      estimatedCost: 21000,
      reason:
        "夜に焼肉を食べたいという明示的な希望と食事時間の条件に合います。",
      crowd: { level: "混雑", scope: "area", areaName: "聖水駅一帯" },
      scoreBreakdown: {
        total: 0.82,
        preference: 0.98,
        crowd: 0.58,
        distance: 0.83,
        time: 1,
        budget: 0.79,
        diversity: 1,
      },
    },
  ],
};
