FROM node:22-alpine AS build
WORKDIR /app

COPY package.json package-lock.json ./
RUN npm ci
COPY . ./

ARG NEXT_PUBLIC_BASE_PATH=/michi
ARG NEXT_PUBLIC_API_URL=/michi/api
ARG NEXT_PUBLIC_DEMO_MODE=false
ARG NEXT_PUBLIC_NAVER_MAP_CLIENT_ID=
ARG NEXT_PUBLIC_LOG_FRIENDS_ENDPOINT=
ENV NEXT_PUBLIC_BASE_PATH=$NEXT_PUBLIC_BASE_PATH \
    NEXT_PUBLIC_API_URL=$NEXT_PUBLIC_API_URL \
    NEXT_PUBLIC_DEMO_MODE=$NEXT_PUBLIC_DEMO_MODE \
    NEXT_PUBLIC_NAVER_MAP_CLIENT_ID=$NEXT_PUBLIC_NAVER_MAP_CLIENT_ID \
    NEXT_PUBLIC_LOG_FRIENDS_ENDPOINT=$NEXT_PUBLIC_LOG_FRIENDS_ENDPOINT
RUN npm run build

FROM node:22-alpine AS runtime
WORKDIR /app
ENV NODE_ENV=production PORT=3000 HOSTNAME=0.0.0.0

COPY --from=build /app/.next/standalone ./
COPY --from=build /app/.next/static ./.next/static

USER node
EXPOSE 3000
CMD ["node", "server.js"]
